### ISSUE TITLE
Bug in transformation application logic  dataset.py 

### ISSUE THREAD

**Issue by Srinjoycode** [ayushmankumar7/Binary-Segmentation-with-Spatial-Attention#1]
In the cityscapesDataset class the transform is not being applied even if a transform  is passed a parameter to the class

**Comment by Srinjoycode** [comment]
@ayushmankumar7  Could you assign me this Issue?

**Comment by ayushmankumar7** [comment]
Sure. Go for it

**Comment by ayushmankumar7** [comment]
> @ayushmankumar7 Could you assign me this Issue?

@Srinjoycode Sure

**Comment by Srinjoycode** [comment]
Kindly check the pull request and merge it if you find it satisfactory

**Comment by ayushmankumar7** [comment]
Thanks for the PR
